### ISSUE TITLE
Add conan recipe

### ISSUE THREAD

**Issue by mailagentrus** [Naios/fluent.cpp#12]
@Naios 

-----

Is it possible to add conan (https://conan.io/ C++ open source package manager) recipe and publish on bintray? It will be really helpful for other depelopers. For example: third party developer can add

`[requires]
continuable/3.0.0@naios/stable`

to own project without any source compilation. If you @Naios want I'll try to prepare basic recipe for win/linux/mac and will prepare pull request.

**Comment by Naios** [comment]
I added a non intrusive conan file which only provides the continuable headers and imports function2 as dependency for the header only mode. CMake targets are not provided yet.
The package is currently only available as `continuable/3.0.0@naios/testing` which reflects the current git revision because 4.0.0 is not fully stable yet and I don't want to backport the conan file changes to the 3.0.0 tag.

I would be open for a contribution which fully adds the capability to use the CMake targets from the conan provided package itself.
