### ISSUE TITLE
Status of the codebase

### ISSUE THREAD

**Issue by Warchant** [Naios/fluent.cpp#15]
@Naios 

Hi. Your library looks wonderful for our use case. 

1. Do you think a codebase is mature enough to be used in production environment?
2. What is the status of 4.0.0? There is no release tag for this version.

**Comment by Naios** [comment]
Hey,
I'm glad that you like the library.

> 1. Do you think a codebase is mature enough to be used in production environment?

Currently there are no bugs known to me except the current issue #13 about a GCC 8+ internal compiler error (which needs a rewrite of the internally used variant implementation, in order apply a workaround for this). I'm using continuable successfully in a personal project of mine, and so far, there was no issue for me. Others are using continuable as well and there were no more reports about defects except of the already fixed ones in the issue tracker.

I can't make any guarantees about the readiness for a production environment, this is also indicated by the license text:
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

However, I would recommend to give the library a try, its API is quite similar to comparable libraries so it should be simple to transition it if doesn't fit into your codebase anymore.

> What is the status of 4.0.0? There is no release tag for this version.

Version 4.0.0 is in progress currently and will be released when some missing planned features are implemented. Currently this is not my highest priority since the library all in all is quite stable in its current state and thus I'm focusing on another project.

However I will try to fix reported major bugs as fast as possible.
Keep in mind that this is an open source project and all work is done on a voluntary basis.

**Comment by Warchant** [comment]
Thank you for the answer.
Gonna add this lib to [hunter](https://hunter.sh) pretty soon :)
