### ISSUE TITLE
Explicit return types for cti::make_continuable<>()

### ISSUE THREAD

**Issue by zerodefect** [Naios/fluent.cpp#6]
@Naios

I appreciate that continuable has been written making heavy use of type erasure.  That is not my problem per-se. The part I'm struggling with is how to explicitly define the return type as specified by ct::make_continuable. What is the type?

```
///////////////////////////////////////////////////////////////////////////
// foo.hpp
///////////////////////////////////////////////////////////////////////////

class foo
{
public:

    enum class foo_result
    {
        ok = 0,
        error = 1,
        // ...
        // ...
    };

    foo() = default;
    ~foo() = default;

    cti::continuable<foo_result> initialise_deferred();
    // ^^^^^^^^^^^^^^^^^^^^^^^^^ - What should the return type be?

    cti::continuable<foo_result> finalise_deferred();
    // ^^^^^^^^^^^^^^^^^^^^^^^^^ - What should the return type be?
};


///////////////////////////////////////////////////////////////////////////
// foo.cpp
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
cti::continuable<foo_result> foo::initialise_deferred()
{
    return cti::make_continuable<foo_result>([](){ // ... });
}

//////////////////////////////////////////////////////////////////////////
cti::continuable<foo_result> foo::finalise_deferred()
{
    return cti::make_continuable<foo_result>([](){ // ... });
}
```

- OS: Linux via Ubuntu 18.04
- Compiler and version: GCC 7.3
- Standard library (if non default): Default (glibc)

**Comment by Naios** [comment]
Basically `cti::make_continuable` returns an unknown (non erased) object which type depends on the result and on the callable object which is passed to `cti::make_continuable`.
The benefit of this technique is that we avoid type erasure until really needed because subsequent calls to `then` won't allocate any memory while being in a non type erased state.

In your example code your **lambdas need to accept a promise object** as depicted by the examples listed in here https://naios.github.io/continuable/tutorial-creating-continuables.html#tutorial-creating-continuables-promises .

Thus you could use `auto` to deduce the return type as shown below:

```cpp
auto foo::initialise_deferred()
{
    return cti::make_continuable<foo_result>([](auto&& promise){ // ... });
}
```

In order to convert the unknown type returned by `cti::make_continuable` to a specific one,
we just convert it to a `cti::continuable<...>` which automatically applies type erasure on the unknown object.

So this is correct:

```cpp
cti::continuable<foo_result> foo::initialise_deferred()
{
    return cti::make_continuable<foo_result>([](auto&& promise){ // ... });
}
```

Also you may do it as following to prevent repetition:

```cpp
cti::continuable<foo_result> foo::initialise_deferred()
{
    return [](auto&& promise){
      // ...
    };
}
```

or

```cpp
cti::continuable<foo_result> foo::initialise_deferred()
{
    return [](cti::promise<foo_result> promise){
      // ...
    };
}
```

Also the library is capable of using a user configured type for error codes see https://naios.github.io/continuable/configuration.html for details.

**Comment by zerodefect** [comment]
Thanks for your assistance, Denis. That was very helfpul. 

I've got some simple code to compile, but I'm now trying a few more difficult things and running into difficulties on how it ought to be solved.

I'm trying nest tasks/continuations. I've written a very loose example of what I'm trying to achieve (probably does not compile).

```
cti::continuable<foo_result> foo::initialise_deferred()
{
    return [](auto &&promise)
    {
        // ...
        // Have some files in varialble 'files'

        // Load some images
        std::vector<cti::continuable<image> > outstanding;

        for (auto &file : files)
        {
            outstanding.emplace_back(
                cti::make_continuable<image>(
                    [file](auto &&promise)
                    {
                        promise.set_value(load_image(file));
                    }));
        }

        return cti::when_all(std::move(outstanding))
            .then([](std::vector<cti::continuable <image> > v)
            {
                return cti::make_ready_continuable(cb_result::CB_S_OK);
            });
    };
}
```

Now, you're probably thinking that I could load all of the images in the outer call, but I must/need to stagger the work to my thread pool (and break work into smaller tasks). I intend to use my own executor at some point.

P.S. - Please let me know if you would prefer this question in a seperate issue ticket.

**Comment by Rogiel** [comment]
@zerodefect Not the author, but on my little game engine I use this library and I load resources somewhat like this (coded from memory, code might not be 100% correct):

	cti::map_pack([](const std::string& file) {
		return cti::make_continuable<image>(
			[file](auto &&promise) {
				thread_pool.post(
					[file, promise = std::forward<decltype(promise)>(promise)]() mutable {
						std::move(promise)(load_image(file));
					});
     			});
	}, files).then([](std::vector<image> images) {
		// :)
	});

You might want to send the results back on the main thread (if you have the means to) by passing a executor to the second argument of `then`, so the you don't have to deal with concurrent access.

**Comment by Naios** [comment]
@Rogiel great example, I like how you used `cti::map_pack` there, probably a `when_all` is missing after you've mapped every file name to a continuable:

```cpp
cti::when_all(cti::map_pack([](const std::string& file) {
	return cti::make_continuable<image>(
		[file](auto &&promise) {
                    // load file here
		});
})).then( ... );
```

I think this solution is quite good since it doesn't apply type erasure on the vector of continuables.

@zerodefect 

Another solution would be to do it as following:

```cpp
auto load_resource(File file) {
    return cti::make_continuable<image>(
                    [file](auto &&promise)
                    {
                        promise.set_value(load_image(file));
                    }));
}

// ...

// Load some images
std::vector<decltype(load_resource(std::declval<File>()))> outstanding;
```

so in this case you also prevent the creation of a type erasure.

Currently the library only supports bulked execution through `when_all` so you are not able to limit the amount of currently lazy executed continuables through the library itself, however you could use a custom executor together with `.then` or in the continuation to do that. However this depends on the executor you are using.
